# Generated by Django 6.0 on 2025-12-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_created',
            new_name='is_completed',
        ),
    ]
